### ISSUE TITLE
如何设置绑定IP 0.0.0.0？

### ISSUE THREAD

**Issue by chenweiyj** [xixilive/wecheat#10]
我启动后只能通过 localhost 访问，不能通过192.168.x.x的ip访问。请问怎么解决？

**Comment by brainet** [comment]
我这边在rackup启动后，直接访问IP地址 `<IP_ADDRESS>:9292`没有问题
你那边尝试过修改hosts做local解析吗？

**Comment by xixilive** [comment]
@chenweiyj 你install的sinatra版本是什么?
